platform :ios, ‘9.0’

source 'https://github.com/146BC/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target ‘Uxi-swift’ do

use_frameworks!
pod 'Graphs', '~> 0.1.2'
pod ‘Alamofire’
pod ’SwiftyJSON’
pod ’SQLite.swift’
pod ’SugarRecord’
pod ‘RAMAnimatedTabBarController’
pod ‘LTMorphingLabel’
pod ‘Cartography’
pod ‘RxSwift’
pod 'StyleKit', '~> 0.3'

end









